/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import config.ImageConfig;

/**
 *
 * @author danae
 */
public class DieField extends javax.swing.JFrame {

    /**
     * Creates new form DieField1
     */
    public DieField() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(981, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setFont(new java.awt.Font("Oswald", 2, 36)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 153));
        backButton.setText("Back to MainMenu");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 390, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ImageConfig.dieField))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        pack();
        setLocationRelativeTo(null);
    }

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {
        this.setVisible(false);
        PreparePanel preparePanel = new PreparePanel();
        preparePanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}