/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import config.ImageConfig;
import config.MusicConfig;
import utils.SoundAndMusic;

/**
 * @author danae
 */
public class PreparePanel extends javax.swing.JFrame {
    PlantsVsZombies i;
    SoundAndMusic BGM = new SoundAndMusic("music/gaming.wav");

    public PreparePanel() {
        this.i = i;
        BGM.StartPlay_BGM();
        initComponents();
    }

    /**
     * Creates new form PreparePanel
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        easyButton = new javax.swing.JButton();
        normalButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PreparePanel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        easyButton.setForeground(new java.awt.Color(51, 102, 255));
        easyButton.setText("Easy");
        easyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyButtonMouseClicked(evt);
            }
        });
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 170, 50));

        normalButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        normalButton.setForeground(new java.awt.Color(51, 51, 255));
        normalButton.setText("Normal");
        normalButton.setPreferredSize(new java.awt.Dimension(119, 59));
        normalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalButtonMouseClicked(evt);
            }
        });
        jPanel1.add(normalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 200, 50));

        hardButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        hardButton.setForeground(new java.awt.Color(51, 102, 255));
        hardButton.setText("Hard");
        hardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardButtonMouseClicked(evt);
            }
        });
        jPanel1.add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ImageConfig.prepareImage))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 617));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyButtonActionPerformed

    public void easyButtonMouseClicked(java.awt.event.MouseEvent evt) {
        mood(10,5,"Easy");
    }

    public void normalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalButtonMouseClicked
        mood(20,7,"Normal");
    }//GEN-LAST:event_normalButtonMouseClicked

    public void hardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseClicked
        mood(30,10,"Hard");
    }//GEN-LAST:event_hardButtonMouseClicked

    private void mood(int zombieNumber,int zombieRandomNumber,String mood){
        i = new PlantsVsZombies();
        BGM.StopPlay_BGM();
        SoundAndMusic a = new SoundAndMusic(MusicConfig.laugh);
        a.playSound(MusicConfig.laugh);
        i.pvz_game = new GameField(i);
        i.pvz_game.newGame(zombieNumber, zombieRandomNumber);
        System.out.println(mood);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PreparePanel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton normalButton;
    // End of variables declaration//GEN-END:variables
}
