/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

<<<<<<< HEAD
import config.ImageConfig;
import config.MusicConfig;
import utils.SoundAndMusic;

/**
=======
import Config.ImageConfig;
import Config.MusicConfig;
import utils.SoundAndMusic;

/**
 *
>>>>>>> master
 * @author danae
 */
public class PreparePanel extends javax.swing.JFrame {
    PlantsVsZombies i;
<<<<<<< HEAD
    SoundAndMusic BGM = new SoundAndMusic("music/gaming.wav");

    public PreparePanel() {
        this.i = i;
        BGM.StartPlay_BGM();
        initComponents();
    }

    /**
     * Creates new form PreparePanel
     */

    /**
=======
//    SoundAndMusic BGM = new SoundAndMusic("music/gaming.wav");
    /**
     * Creates new form PreparePanel1
     */
    public PreparePanel() {
        initComponents();
        this.i = i;
//        BGM.StartPlay_BGM();
    }

    /**
>>>>>>> master
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jPanel1 = new javax.swing.JPanel();
        easyButton = new javax.swing.JButton();
        normalButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PreparePanel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        easyButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        easyButton.setForeground(new java.awt.Color(51, 102, 255));
        easyButton.setText("Easy");
        easyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyButtonMouseClicked(evt);
            }
        });
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 170, 50));

        normalButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        normalButton.setForeground(new java.awt.Color(51, 51, 255));
        normalButton.setText("Normal");
        normalButton.setPreferredSize(new java.awt.Dimension(119, 59));
        normalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                normalButtonMouseClicked(evt);
            }
        });
        jPanel1.add(normalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, 200, 50));

        hardButton.setFont(new java.awt.Font("Lucida Handwriting", 2, 36)); // NOI18N
        hardButton.setForeground(new java.awt.Color(51, 102, 255));
        hardButton.setText("Hard");
        hardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardButtonMouseClicked(evt);
            }
        });
        jPanel1.add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ImageConfig.prepareImage))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 617));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));
=======
        EasyButton = new javax.swing.JButton();
        NormalButton = new javax.swing.JButton();
        HardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EasyButton.setBackground(new java.awt.Color(255, 204, 0));
        EasyButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        EasyButton.setText("Easy");
        EasyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EasyButtonMouseClicked(evt);
            }
        });
        getContentPane().add(EasyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 200, 60));

        NormalButton.setBackground(new java.awt.Color(255, 204, 0));
        NormalButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        NormalButton.setText("Normal");
        NormalButton.setMaximumSize(new java.awt.Dimension(107, 57));
        NormalButton.setMinimumSize(new java.awt.Dimension(107, 57));
        NormalButton.setPreferredSize(new java.awt.Dimension(107, 57));
        NormalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NormalButtonMouseClicked(evt);
            }
        });
        getContentPane().add(NormalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 200, 60));

        HardButton.setBackground(new java.awt.Color(255, 204, 0));
        HardButton.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        HardButton.setText("Hard");
        HardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HardButtonMouseClicked(evt);
            }
        });
        getContentPane().add(HardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, 200, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ImageConfig.preparePanel))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 634));
>>>>>>> master

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyButtonActionPerformed

    public void easyButtonMouseClicked(java.awt.event.MouseEvent evt) {
        mood(10,5,"Easy");
    }

    public void normalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalButtonMouseClicked
        mood(20,7,"Normal");
    }//GEN-LAST:event_normalButtonMouseClicked

    public void hardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseClicked
        mood(30,10,"Hard");
    }//GEN-LAST:event_hardButtonMouseClicked

    private void mood(int zombieNumber,int zombieRandomNumber,String mood){
        i = new PlantsVsZombies();
        BGM.StopPlay_BGM();
        SoundAndMusic a = new SoundAndMusic(MusicConfig.laugh);
        a.playSound(MusicConfig.laugh);
=======
    private void EasyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyButtonMouseClicked
        mood(10,5,"Easy");
    }//GEN-LAST:event_EasyButtonMouseClicked

    private void NormalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NormalButtonMouseClicked
        mood(20,7,"Normal");
    }//GEN-LAST:event_NormalButtonMouseClicked

    private void HardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardButtonMouseClicked
        mood(30,10,"Hard");
    }//GEN-LAST:event_HardButtonMouseClicked
    private void mood(int zombieNumber,int zombieRandomNumber,String mood){
        SoundAndMusic a = new SoundAndMusic(MusicConfig.laugh);
        a.playSound(MusicConfig.laugh);
        i = new PlantsVsZombies();
//        BGM.StopPlay_BGM();
>>>>>>> master
        i.pvz_game = new GameField(i);
        i.pvz_game.newGame(zombieNumber, zombieRandomNumber);
        System.out.println(mood);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
<<<<<<< HEAD
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PreparePanel().setVisible(true);
=======
//            java.util.logging.Logger.getLogger(PreparePanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PreparePanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PreparePanel1().setVisible(true);
>>>>>>> master
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton normalButton;
=======
    private javax.swing.JButton EasyButton;
    private javax.swing.JButton HardButton;
    private javax.swing.JButton NormalButton;
    private javax.swing.JLabel jLabel1;
>>>>>>> master
    // End of variables declaration//GEN-END:variables
}
